### ISSUE TITLE
Suggestion: Release a version of Cake.SharePoint compatible with Cake 1.0.0

### ISSUE THREAD

**Issue by nils-a** [JeroenVandezande/Cake.SharePoint#4]
https://cakebuild.net/blog/2021/02/cake-v1.0.0-released

🙂

**Comment by pascalberger** [comment]
I saw that [version 1.2.0](https://www.nuget.org/packages/Cake.SharePoint/1.2.0) was released build against Cake 1.1.0. Note that for best compatibility suggestion is to build against the lowest API compatible version, as long as no newer features are required, which currently is 1.0.0. See https://cakebuild.net/docs/extending/addins/best-practices#references for details.

**Comment by JeroenVandezande** [comment]
I am in progress of getting a new build out that will reference 1.0.0...
I do have a question, Microsoft changed the way you need to authenticate with Sharepoint using their Nuget Package library that I use.
So my next release will be a breaking change, what is the policy for this? increase the major version?

**Comment by pascalberger** [comment]
We currently don't have any official best practices defined for addin authors what versioning to follow. That said, Cake itself and most addins follow [SemVer](https://semver.org/) which would mean to bump major version in this case.

**Comment by JeroenVandezande** [comment]
BTW does cake resolve NuGet dependencies when using an add-in that has Nuget dependencies?

**Comment by pascalberger** [comment]
> BTW does cake resolve NuGet dependencies when using an add-in that has Nuget dependencies?

For Cake Frosting default NuGet clients are used which resolve dependencies (and you can manage versions of dependency in your project). For Cake Scripting, the [addin directive](https://cakebuild.net/docs/writing-builds/preprocessor-directives/addin) does not load dependencies by default. The user can enforce this through the [loaddependencies parameter](https://cakebuild.net/docs/writing-builds/preprocessor-directives/addin#dependencies). When different addins require different incompatible versions of the same dependency this will lead to issues at runtime.

**Comment by JeroenVandezande** [comment]
A new package has been published, now referencing Cake 1.0.0
